import{useEffect,useState}from'react';import{SITE}from'./config/site.js';import{WORKS,FEED}from'./data/works.js';import{paymentProvider}from'./payment/provider.js';
function Fox({small=false}){return <svg className={small?'fox small':'fox'} viewBox="0 0 100 100" aria-hidden="true"><path d="M18 72 14 22l27 15 9-7 9 7 27-15-4 50-16 13H34L18 72Z" fill="currentColor"/><path d="m27 38 13 7-9 11-8-7m50-11-13 7 9 11 8-7M39 68c7 6 15 8 22 0l-11-12-11 12Z" fill="#0b0a09"/></svg>}
function SafeImage({src,alt,className=''}){const[failed,setFailed]=useState(false);return failed?<div className={'image-fallback '+className} role="img" aria-label={alt}><Fox/></div>:<img className={className} src={src} alt={alt} loading="lazy" onError={()=>setFailed(true)}/>;}
export default function App(){const[pay,setPay]=useState(null),[light,setLight]=useState(null),[menu,setMenu]=useState(false);
useEffect(()=>{document.body.classList.toggle('locked',!!(pay||light));const key=e=>{if(e.key==='Escape'){setPay(null);setLight(null)}if(light&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();move(e.key==='ArrowRight'?1:-1)}};window.addEventListener('keydown',key);return()=>{document.body.classList.remove('locked');window.removeEventListener('keydown',key)}},[pay,light]);
const order=async x=>setPay(await paymentProvider.prepare({title:x?.title})),close=()=>setLight(null),move=d=>{if(!light)return;const a=light._list||WORKS,i=a.findIndex(x=>x.id===light.id);setLight(a[(i+d+a.length)%a.length])};
const open=(x,list)=>setLight({...x,_list:list});
return <div className="site"><header><a className="brand" href="#top" aria-label="ALI — на главную" onClick={()=>setMenu(false)}><b><Fox small/></b>ALI</a><button className="hamb" aria-label={menu?'Закрыть меню':'Открыть меню'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'×':'☰'}</button><nav className={menu?'nav open':'nav'} aria-label="Основная навигация"><a href="#works" onClick={()=>setMenu(false)}>Работы</a><a href="#feed" onClick={()=>setMenu(false)}>Лента</a><a href="#about" onClick={()=>setMenu(false)}>О мастере</a><a href="#order" onClick={()=>setMenu(false)}>Заказ</a></nav><a className="tg header-cta" href={SITE.orderUrl} target="_blank" rel="noreferrer">Написать мастеру ↗</a></header>
<main id="top"><section className="hero"><div><p className="eyebrow">atelier · custom clothing</p><h1>ОДЕЖДА,<br/><i>КОТОРОЙ</i><br/>БОЛЬШЕ НЕТ.</h1><p className="lead">{SITE.tagline} Кастомные вещи и авторские детали без массового производства.</p><div className="actions"><a className="btn dark" href="#works">Смотреть работы ↓</a><a className="under" href={SITE.orderUrl} target="_blank" rel="noreferrer">Обсудить идею ↗</a></div></div><div className="hero-photo"><SafeImage src={WORKS[0].src} alt="Работа ALI"/><span className="fox-badge"><Fox/></span><strong>ONE<br/>OF ONE</strong></div></section>
<section id="works" className="section"><div className="head"><div><p className="eyebrow">01 / portfolio</p><h2>Работы</h2></div><p>Архив готовых кастомов. Выберите работу, чтобы рассмотреть её подробнее.</p></div><div className="gallery">{WORKS.map((x,i)=><button className={'work w'+i} onClick={()=>open(x,WORKS)} key={x.id} aria-label={'Открыть '+x.title}><SafeImage src={x.src} alt={x.title}/><span><b>{x.title}</b><small>{x.label}</small><em>Открыть ↗</em></span></button>)}</div></section>
<section id="feed" className="section feed"><div className="head"><div><p className="eyebrow">02 / photo archive</p><h2>Лента</h2></div><p>Отдельные фотографии работ, деталей и процесса. Новые материалы можно добавлять без изменения структуры сайта.</p></div><div className="feed-grid">{FEED.map((x,i)=><article className={'feed-item '+(i===0?'featured':'')} onClick={()=>open(x,FEED)} key={x.id} tabIndex="0" role="button" onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')open(x,FEED)}}><div className="media"><SafeImage src={x.src} alt={x.title}/><span className="media-index">0{i+1}</span><span className="media-open" aria-hidden="true">↗</span></div><div className="feed-copy"><p className="eyebrow">{x.type} · {x.date}</p><h3>{x.title}</h3><p>{x.text}</p><b>Открыть работу ↗</b></div></article>)}</div></section>
<section id="about" className="dark-section"><div className="fox-card"><Fox/></div><div><p className="eyebrow">03 / philosophy</p><h2>Не просто<br/><i>одежда.</i></h2><p>Идея, характер и референсы превращаются в вещь, которая существует в одном экземпляре.</p><small>Крой · ручная работа · кастомизация</small></div></section>
<section id="order" className="section"><div className="head"><div><p className="eyebrow">04 / process</p><h2>Как заказать</h2></div><a className="btn outline" href={SITE.orderUrl} target="_blank" rel="noreferrer">Начать заказ ↗</a></div><div className="steps">{[['01','Идея','Фото, референс или описание.'],['02','Обсуждение','Размер, материал, сроки и цена.'],['03','Создание','Мастер делает вещь и показывает процесс.'],['04','Готово','Оплата и отправка заказа.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="cta"><Fox/><p className="eyebrow">05 / start a project</p><h2>Есть идея?<br/><i>Давайте сделаем.</i></h2><a className="btn light" href={SITE.orderUrl} target="_blank" rel="noreferrer">Написать мастеру ↗</a></section></main><footer><span>ALI · custom clothing · one of one</span><a href={SITE.telegramUrl} target="_blank" rel="noreferrer">@VespidKitten875 ↗</a></footer>
{pay&&<div className="overlay" role="dialog" aria-modal="true" aria-label="Оформление заказа" onClick={()=>setPay(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Закрыть" onClick={()=>setPay(null)}>×</button><p className="eyebrow">ORDER / PLATEGA</p><h2>Оплата</h2><p>{pay.message}</p><a className="btn dark full" href={pay.telegramUrl} target="_blank" rel="noreferrer">Перейти к мастеру в Telegram ↗</a></div></div>}
{light&&<div className="overlay viewer" onClick={close} role="dialog" aria-modal="true" aria-label={light.title}><div className="viewer-box" onClick={e=>e.stopPropagation()}><button className="viewer-close" aria-label="Закрыть" onClick={close}>×</button><button className="viewer-prev" aria-label="Предыдущая работа" onClick={()=>move(-1)}>←</button><SafeImage src={light.src} alt={light.title}/><button className="viewer-next" aria-label="Следующая работа" onClick={()=>move(1)}>→</button><div><p className="eyebrow">{light.label||light.type}</p><h2>{light.title}</h2>{light.text&&<p className="viewer-text">{light.text}</p>}<button className="btn dark" onClick={()=>{close();order(light)}}>Заказать ↗</button></div></div></div>}</div>}