import{useEffect,useRef,useState}from'react';import{SITE,DELIVERY}from'./config/site.js';import{WORKS,FEED}from'./data/works.js';import{paymentProvider}from'./payment/provider.js';

function Fox({small=false}){return <svg className={small?'fox small':'fox'} viewBox="0 0 100 100" aria-hidden="true"><path d="M18 72 14 22l27 15 9-7 9 7 27-15-4 50-16 13H34L18 72Z" fill="currentColor"/><path d="m27 38 13 7-9 11-8-7m50-11-13 7 9 11 8-7M39 68c7 6 15 8 22 0l-11-12-11 12Z" fill="#080808"/></svg>}
function SafeImage({src,alt,className='',loading='lazy'}){const[failed,setFailed]=useState(false);return failed?<div className={'image-fallback '+className} role="img" aria-label={alt}><span>PHOTO<br/>UNAVAILABLE</span></div>:<img className={className} src={src} alt={alt} loading={loading} decoding="async" onError={()=>setFailed(true)}/>;}

export default function App(){const[pay,setPay]=useState(null),[light,setLight]=useState(null),[menu,setMenu]=useState(false);const lastFocus=useRef(null);const payDialogRef=useRef(null),lightDialogRef=useRef(null);
useEffect(()=>{document.body.classList.toggle('locked',!!(pay||light));const key=e=>{if(e.key==='Escape'){setPay(null);setLight(null);setMenu(false);return}if(light&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();move(e.key==='ArrowRight'?1:-1)}};window.addEventListener('keydown',key);return()=>{document.body.classList.remove('locked');window.removeEventListener('keydown',key)}},[pay,light]);
useEffect(()=>{const active=pay||light;if(!active){if(lastFocus.current?.isConnected)lastFocus.current.focus();lastFocus.current=null;return}if(!lastFocus.current)lastFocus.current=document.activeElement;const root=(pay?payDialogRef:lightDialogRef).current;if(!root)return;const focusable=root.querySelectorAll('button,a[href],input,select,textarea,[tabindex]:not([tabindex="-1"])');if(focusable[0])focusable[0].focus();const trap=e=>{if(e.key!=='Tab'||!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};root.addEventListener('keydown',trap);return()=>root.removeEventListener('keydown',trap)},[pay,light]);
useEffect(()=>{const nodes=[...document.querySelectorAll('.reveal')];if(!('IntersectionObserver'in window)){nodes.forEach(n=>n.classList.add('is-visible'));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -8% 0px'});nodes.forEach(n=>observer.observe(n));return()=>observer.disconnect()},[]);
useEffect(()=>{const update=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;const progress=max>0?window.scrollY/max:0;document.documentElement.style.setProperty('--scroll-progress',progress.toFixed(4))};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);
const order=async x=>{const result=await paymentProvider.prepare({title:x?.title});setPay(result);setLight(null)},close=()=>setLight(null),move=d=>{if(!light)return;const a=light._list||WORKS,i=a.findIndex(x=>x.id===light.id);setLight(a[(i+d+a.length)%a.length])};const open=(x,list)=>setLight({...x,_list:list});
return <div className="site"><div className="scroll-progress" aria-hidden="true"><span/></div><a className="skip-link" href="#works">Перейти к работам</a><header><a className="brand" href="#top" aria-label="AliPay — на главную" onClick={()=>setMenu(false)}><b><Fox small/></b>AliPay</a><button className="hamb" aria-label={menu?'Закрыть меню':'Открыть меню'} aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>{menu?'×':'☰'}</button><nav className={menu?'nav open':'nav'} aria-label="Основная навигация"><a href="#works" onClick={()=>setMenu(false)}>Работы</a><a href="#feed" onClick={()=>setMenu(false)}>Лента</a><a href="#about" onClick={()=>setMenu(false)}>Как работаем</a><a href="#delivery" onClick={()=>setMenu(false)}>Доставка</a><a href="#order" onClick={()=>setMenu(false)}>Заказ</a></nav><a className="tg header-cta" href={SITE.orderUrl} target="_blank" rel="noreferrer">Написать в Telegram ↗</a></header>
<main id="top"><section className="hero reveal"><div><p className="eyebrow">custom print studio · 01</p><h1>ТВОЙ<br/><i>РИСУНОК.</i><br/>ТВОЯ ВЕЩЬ.</h1><p className="lead">Рисуем и наносим согласованный дизайн на готовые вещи. Можно выбрать нашу футболку или шоппер — или прислать любую подходящую вещь клиента.</p><div className="actions"><a className="btn dark" href="#works">Смотреть работы ↓</a><a className="under" href={SITE.orderUrl} target="_blank" rel="noreferrer">Обсудить идею ↗</a></div></div><div className="hero-photo reveal reveal-delay-1"><SafeImage src={WORKS[0].src} alt="Нанесение рисунка на футболку" loading="eager"/><span className="fox-badge"><Fox/></span><strong>DRAW<br/>APPLY<br/>REPEAT</strong><span className="hero-orbit" aria-hidden="true">●</span></div></section>
<section id="works" className="section reveal"><div className="head"><div><p className="eyebrow">02 / portfolio</p><h2>Работы</h2></div><p>Три реальные категории: наша футболка, наш шоппер и вещи клиентов. Только готовая основа и нанесение рисунка.</p></div><div className="gallery">{WORKS.map((x,i)=><button type="button" className={'work w'+i} onClick={()=>open(x,WORKS)} key={x.id} aria-label={'Открыть '+x.title}><SafeImage src={x.src} alt={x.title}/><span><b>{x.title}</b><small>{x.label}</small><em>Открыть ↗</em></span></button>)}</div></section>
<section id="feed" className="section feed reveal"><div className="head"><div><p className="eyebrow">03 / archive</p><h2>Лента</h2></div><p>Фото работ, деталей и этапов нанесения. Лента обновляется без изменения структуры сайта.</p></div><div className="feed-grid">{FEED.map((x,i)=><button aria-label={'Открыть '+x.title} className={'feed-item '+(i===0?'featured':'')} onClick={()=>open(x,FEED)} key={x.id} type="button"><div className="media"><SafeImage src={x.src} alt={x.title}/><span className="media-index">0{i+1}</span><span className="media-open" aria-hidden="true">↗</span></div><div className="feed-copy"><p className="eyebrow">{x.type} · {x.date}</p><h3>{x.title}</h3><p>{x.text}</p><b>Открыть ↗</b></div></button>)}</div></section>
<section id="about" className="dark-section reveal"><div className="fox-card"><Fox/><span>ALI / PAY</span></div><div><p className="eyebrow">04 / two ways</p><h2>Два способа<br/><i>сделать кастом.</i></h2><div className="work-modes"><article><b>01</b><h3>Наша футболка<br/>или шоппер</h3><p>Выбираете готовую основу AliPay, а мы наносим на неё согласованный рисунок.</p></article><article><b>02</b><h3>Любая вещь клиента</h3><p>Присылаете свою подходящую вещь — футболку, худи, куртку, шоппер или другой текстиль.</p></article></div><small>Рисунок → согласование → нанесение · только готовые вещи</small></div></section>
<section id="delivery" className="section delivery reveal"><div className="delivery-intro"><div><p className="eyebrow">05 / delivery</p><h2>Отправим<br/><i>по России.</i></h2></div><div><p>После готовности заказ отправляется удобным для клиента способом. Службу доставки согласовываем перед отправкой.</p><span className="delivery-note">3 распространённых варианта</span></div></div><div className="delivery-grid">{DELIVERY.map((x,i)=><a className="delivery-card" href={x.url} target="_blank" rel="noreferrer" key={x.name}><div className="delivery-top"><span>0{i+1}</span><span>DELIVERY</span></div><div className="delivery-logo"><img src={x.logo} alt={x.name} loading="lazy" decoding="async"/></div><div className="delivery-copy"><h3>{x.name}</h3><p>{x.text}</p></div><span className="delivery-link">Сайт службы ↗</span></a>)}</div></section>
<section id="order" className="section reveal"><div className="head"><div><p className="eyebrow">06 / process</p><h2>Как заказать</h2></div><a className="btn outline" href={SITE.orderUrl} target="_blank" rel="noreferrer">Начать заказ ↗</a></div><div className="steps">{[['01','Идея','Фото, референс или описание рисунка.'],['02','Основа','Наша футболка или шоппер — либо вещь клиента.'],['03','Нанесение','Согласовываем рисунок, расположение и наносим его.'],['04','Отправка','Согласовываем оплату и удобный способ доставки.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="cta reveal"><Fox/><p className="eyebrow">07 / start</p><h2>Есть идея?<br/><i>Покажите её нам.</i></h2><a className="btn light" href={SITE.orderUrl} target="_blank" rel="noreferrer">Написать в Telegram ↗</a></section></main><footer><span>AliPay · custom prints · готовая вещь + рисунок</span><a href={SITE.telegramUrl} target="_blank" rel="noreferrer">@VespidKitten875 ↗</a></footer>
{pay&&<div ref={payDialogRef} className="overlay" role="dialog" aria-modal="true" aria-labelledby="payment-title" onClick={()=>setPay(null)}><div className="modal glass" onClick={e=>e.stopPropagation()}><button type="button" className="modal-close" aria-label="Закрыть" onClick={()=>setPay(null)}>×</button><p className="eyebrow">ORDER / CONTACT</p><h2 id="payment-title">Оформление заказа</h2><p>{pay.message}</p><a className="btn dark full" href={pay.telegramUrl} target="_blank" rel="noreferrer">Перейти в Telegram ↗</a></div></div>}
{light&&<div ref={lightDialogRef} className="overlay viewer" onClick={close} role="dialog" aria-label="Просмотр работ" aria-modal="true" aria-labelledby="viewer-title"><div className="viewer-box glass" onClick={e=>e.stopPropagation()}><button type="button" className="viewer-close" aria-label="Закрыть" onClick={close}>×</button><button type="button" className="viewer-prev" aria-label="Предыдущая работа" onClick={()=>move(-1)}>←</button><SafeImage src={light.src} alt={light.title}/><button type="button" className="viewer-next" aria-label="Следующая работа" onClick={()=>move(1)}>→</button><div><p className="eyebrow">{light.label||light.type}</p><h2 id="viewer-title">{light.title}</h2>{light.text&&<p className="viewer-text">{light.text}</p>}<button className="btn dark" onClick={()=>order(light)}>Заказать ↗</button></div></div></div>}</div>}
